# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: sb-ble 0.5.0 ruby lib

Gem::Specification.new do |s|
  s.name = "sb-ble".freeze
  s.version = "0.5.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Fred Mitchell & Sensorberg".freeze]
  s.date = "2017-05-23"
  s.description = "This supports LE Advertising".freeze
  s.email = "frederick.mitchell@sensorberg.com".freeze
  s.executables = ["rble".freeze]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.org"
  ]
  s.files = [
    ".rspec",
    ".semver",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.org",
    "Rakefile",
    "bin/rble",
    "lib/ble.rb",
    "lib/ble/adapter.rb",
    "lib/ble/agent.rb",
    "lib/ble/char_desc.rb",
    "lib/ble/char_registry.rb",
    "lib/ble/characteristic.rb",
    "lib/ble/db_eddystone.rb",
    "lib/ble/db_nordic.rb",
    "lib/ble/db_sig_characteristic.rb",
    "lib/ble/db_sig_service.rb",
    "lib/ble/device.rb",
    "lib/ble/notifications.rb",
    "lib/ble/service.rb",
    "lib/ble/uuid.rb",
    "lib/ble/version.rb",
    "sb-ble.gemspec",
    "spec/ruby-ble_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/flajann2/ruby-ble".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.6.11".freeze
  s.summary = "Bluetooth Low Energy for Ruby -- Sensorberg Version".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ruby-dbus>.freeze, ["~> 0"])
      s.add_runtime_dependency(%q<semver2>.freeze, ["~> 3"])
      s.add_development_dependency(%q<rspec>.freeze, ["~> 3"])
      s.add_development_dependency(%q<yard>.freeze, ["~> 0"])
      s.add_development_dependency(%q<rdoc>.freeze, ["~> 3"])
      s.add_development_dependency(%q<bundler>.freeze, ["~> 1"])
      s.add_development_dependency(%q<juwelier>.freeze, ["~> 2"])
      s.add_development_dependency(%q<simplecov>.freeze, [">= 0"])
      s.add_development_dependency(%q<pry>.freeze, ["~> 0"])
      s.add_development_dependency(%q<pry-byebug>.freeze, ["~> 3"])
      s.add_development_dependency(%q<pry-doc>.freeze, ["~> 0"])
      s.add_development_dependency(%q<pry-remote>.freeze, ["~> 0"])
      s.add_development_dependency(%q<pry-rescue>.freeze, ["~> 1"])
      s.add_development_dependency(%q<pry-stack_explorer>.freeze, ["~> 0"])
      s.add_development_dependency(%q<redcarpet>.freeze, [">= 0"])
      s.add_development_dependency(%q<github-markup>.freeze, [">= 0"])
    else
      s.add_dependency(%q<ruby-dbus>.freeze, ["~> 0"])
      s.add_dependency(%q<semver2>.freeze, ["~> 3"])
      s.add_dependency(%q<rspec>.freeze, ["~> 3"])
      s.add_dependency(%q<yard>.freeze, ["~> 0"])
      s.add_dependency(%q<rdoc>.freeze, ["~> 3"])
      s.add_dependency(%q<bundler>.freeze, ["~> 1"])
      s.add_dependency(%q<juwelier>.freeze, ["~> 2"])
      s.add_dependency(%q<simplecov>.freeze, [">= 0"])
      s.add_dependency(%q<pry>.freeze, ["~> 0"])
      s.add_dependency(%q<pry-byebug>.freeze, ["~> 3"])
      s.add_dependency(%q<pry-doc>.freeze, ["~> 0"])
      s.add_dependency(%q<pry-remote>.freeze, ["~> 0"])
      s.add_dependency(%q<pry-rescue>.freeze, ["~> 1"])
      s.add_dependency(%q<pry-stack_explorer>.freeze, ["~> 0"])
      s.add_dependency(%q<redcarpet>.freeze, [">= 0"])
      s.add_dependency(%q<github-markup>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<ruby-dbus>.freeze, ["~> 0"])
    s.add_dependency(%q<semver2>.freeze, ["~> 3"])
    s.add_dependency(%q<rspec>.freeze, ["~> 3"])
    s.add_dependency(%q<yard>.freeze, ["~> 0"])
    s.add_dependency(%q<rdoc>.freeze, ["~> 3"])
    s.add_dependency(%q<bundler>.freeze, ["~> 1"])
    s.add_dependency(%q<juwelier>.freeze, ["~> 2"])
    s.add_dependency(%q<simplecov>.freeze, [">= 0"])
    s.add_dependency(%q<pry>.freeze, ["~> 0"])
    s.add_dependency(%q<pry-byebug>.freeze, ["~> 3"])
    s.add_dependency(%q<pry-doc>.freeze, ["~> 0"])
    s.add_dependency(%q<pry-remote>.freeze, ["~> 0"])
    s.add_dependency(%q<pry-rescue>.freeze, ["~> 1"])
    s.add_dependency(%q<pry-stack_explorer>.freeze, ["~> 0"])
    s.add_dependency(%q<redcarpet>.freeze, [">= 0"])
    s.add_dependency(%q<github-markup>.freeze, [">= 0"])
  end
end

